# pipenv and pytest execution inspired by
# https://github.com/okeeffed/hello-pytest-github-actions/

name: Windows
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        run: |
          pipenv run pytest --verbose --capture=tee-sys
